# Pipeline for building and deploying a Dockerized Next.js app to Azure App Service

trigger:
- main

variables:
  # Link variable group from the Library
  - group: dev

  # --- Configuración de Docker y Azure ---
  - name: dockerRegistryServiceConnection
    value: 'ACRConnection'
  - name: imageRepository
    value: 'frontsoftwareseguro'
  - name: containerRegistry
    value: 'softwareseguro.azurecr.io'
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

  # --- Configuración de la App de Azure ---
  - name: azureSubscription
    value: '5c9d109b-9f54-4fab-94e6-36ea3326c6ca'
  - name: webAppName
    value: 'softwareseguro'

  # --- Configuración del Agente del Pipeline ---
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: 'Build and push image to ACR'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
        arguments: '--build-arg DATABASE_URL=$(DATABASE_URL)'

- stage: Deploy
  displayName: 'Deploy to App Service'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy # Changed from 'deployment' to 'job'
    displayName: 'Deploy App Service'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy to Azure App Service'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        imageName: '$(containerRegistry)/$(imageRepository):$(tag)'
        appSettings: '-WEBSITES_PORT 3000'
